---
title: "Task #1 EDS 221"
author: "Dalila Lara"
format: html
editor: visual
---
### Loading packages 
```{r}
library(tidyverse)
library(janitor)
library(skimr)
```

### Calling in data 
```{r}
stl_lead <- read_delim(here::here("data", "stl_blood_lead.csv"))

stl_lead <- clean_names(stl_lead)
```

### Viewing data
```{r}
head(stl_lead)
skim(stl_lead)
names(stl_lead)
glimpse(stl_lead)
```

### Adding new column to data
```{r}
stl_lead_prop <- stl_lead %>% mutate(prop_white = (white/total_pop) * 100)
```

### Scatter Plot
```{r}
stl_lead_plot <- ggplot(data = stl_lead_prop,
       aes(x = pct_elevated,
           y = white)) + 
  geom_point(aes(color = white)) +
  theme_minimal() +
  labs(title = "People with elevated PCT",
       x = "White", 
       y = "Pct Elevated")
stl_lead_plot
```

In the demographic we observe a trend in which PCT Elevated levels are within the 0 to 4000 range for the population identifying as white.  


### Saving Graph
```{r}
ggsave(here::here("figs", "stl_lead_plot.png"),
       height = 6,
       width = 5)
```

### Histogram
```{r}
pct_elevated_plot <- ggplot(data = stl_lead_prop, aes(x = pct_elevated)) + geom_histogram() + labs(title = "PCT Elevated",
       x = "PCT elevated", 
       y = "Count")

pct_elevated_plot

ggsave(here::here("figs", "pct_elevated_plot.png"),
       height = 6,
       width = 5)
```


